name: prophet_env
channels:
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - annotated-types=0.6.0
  - anyio=4.10.0
  - aom=3.6.0
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0=openblas
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
